// Package mshark is a simple packet capture tool
package mshark

import (
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/signal"
	"strings"
	"time"

	"github.com/shadowy-pycoder/mshark/layers"
	"github.com/shadowy-pycoder/mshark/network"
)

var colorMap = map[int]string{ // TODO (shadowy-pycoder): add colors from shadowy-pycoder/colors
	0: "\033[37m",
	1: "\033[36m",
	2: "\033[32m",
	3: "\033[33m",
	4: "\033[35m",
}
var packetDelimeter = "\033[37m" + strings.Repeat("─", 66) + "\033[0m"

var _ PacketWriter = &Writer{}

type PacketWriter interface {
	WritePacket(timestamp time.Time, data []byte) error
}

type Config struct {
	Device       *net.Interface // The name of the network interface ("any" means listen on all interfaces).
	Snaplen      int            // The maximum length of each packet snapshot.
	Promisc      bool           // Promiscuous mode. This setting is ignored for "any" interface.
	Timeout      time.Duration  // The maximum deadline for new packet to arrive
	PacketCount  int            // The maximum number of packets to capture.
	PacketBuffer int            // The maximum size for packet buffer (Default: 8192)
	Expr         string         // BPF filter expression.
}

type Writer struct {
	w       io.Writer
	packets uint64
	stdout  bool
	verbose bool
}

// NewWriter creates a new mshark Writer.
func NewWriter(w io.Writer, verbose bool) *Writer {
	return &Writer{
		w:       w,
		stdout:  w == os.Stdout,
		verbose: verbose,
	}
}

// printPacket prints a layer packet to the writer. If the writer is an instance of os.Stdout,
// the packet will be printed with color, based on the layerNum.
func (mw *Writer) printPacket(layer layers.Layer, layerNum int) {
	var packet string
	if mw.verbose {
		packet = layer.String()
	} else {
		packet = layer.Summary()
	}
	if mw.stdout {
		if color, ok := colorMap[layerNum]; ok {
			packet = color + packet + "\033[0m"
		}
	}
	fmt.Fprintln(mw.w, packet)
}

// WritePacket writes a packet to the writer, along with its timestamp.
//
// Timestamps are to be generated by the calling code.
func (mw *Writer) WritePacket(timestamp time.Time, data []byte) error {
	mw.packets++
	fmt.Fprintf(mw.w, "- Packet: %d Timestamp: %s\n", mw.packets, timestamp.Format("2006-01-02T15:04:05.000000-0700"))
	fmt.Fprintln(mw.w, packetDelimeter)
	next := layers.GetLayer(layers.LayerETH)
	if next == nil {
		return nil
	}
	if err := next.Parse(data); err != nil {
		return err
	}
	var layerNum int
	mw.printPacket(next, layerNum)
	for {
		next = next.NextLayer()
		if next == nil {
			return nil
		}
		layerNum++
		mw.printPacket(next, layerNum)
	}
}

// WriteHeader writes a header to the writer.
//
// The header contains metadata about the capture, such as the interface name,
// snapshot length, promiscuous mode, timeout, number of packets, and BPF filter.
//
// The header is written in the following format:
//
//   - Interface: eth0
//   - Snapshot Length: 65535
//   - Promiscuous Mode: true
//   - Timeout: 5s
//   - Number of Packets: 0
//   - Packet Buffer Size: 8192
//   - BPF Filter: "ip proto tcp"
//   - Verbose: true
func (mw *Writer) WriteHeader(c *Config) error {
	_, err := fmt.Fprintf(mw.w, `- Interface: %s
- Snapshot Length: %d
- Promiscuous Mode: %v
- Timeout: %s
- Number of Packets: %d
- Packet Buffer Size: %d
- BPF Filter: %q
- Verbose: %v

`,
		c.Device.Name,
		c.Snaplen,
		c.Device.Name != "any" && c.Promisc,
		c.Timeout,
		c.PacketCount,
		c.PacketBuffer,
		c.Expr,
		mw.verbose,
	)
	return err
}

// OpenLive opens a live capture based on the given configuration and writes
// all captured packets to the given PacketWriters.
func OpenLive(conf *Config, pw ...PacketWriter) error {
	lc := &network.ListenConfig{Device: conf.Device, FilterExpr: conf.Expr}
	// setting promisc mode
	if conf.Device.Name != "any" {
		lc.Promiscuous = &conf.Promisc
	}
	c, err := network.ListenPacket(lc)
	if err != nil {
		return err
	}
	done := make(chan bool)

	defer func() {
		stats, err := c.Stats()
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to fetch stats: %v", err)
		} else {
			fmt.Printf("- Packets: %d, Drops: %d, Freeze Queue Count: %d\n",
				stats.Packets, stats.Drops, stats.FreezeQueueCount)
			for _, w := range pw {
				if w, ok := w.(*Writer); ok && w.w == os.Stdout {
					fmt.Fprintf(w.w, "- Packets Captured: %d\n", w.packets)
					break
				}
			}
		}
		// close Conn
		err = c.Close()
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed closing connection: %v", err)
		}
	}()

	go func() {
		quit := make(chan os.Signal, 1)
		signal.Notify(quit, os.Interrupt)
		<-quit
		c.SetDeadline(time.Now().Add(5 * time.Second))
		close(done)
	}()

	// number of packets
	count := max(0, conf.PacketCount)
	infinity := count == 0

	b := make([]byte, conf.Snaplen)
	if conf.PacketBuffer <= 0 {
		conf.PacketBuffer = 8192
	}
	packetQueue := make(chan []byte, conf.PacketBuffer)

	go func() {
		for {
			select {
			case <-done:
				return
			case packet, ok := <-packetQueue:
				if !ok {
					return
				}
				for _, w := range pw {
					w.WritePacket(time.Now().UTC(), packet)
				}
			}
		}
	}()

	for i := 0; infinity || i < count; i++ {
		select {
		case <-done:
			close(packetQueue)
			return nil
		default:
			if conf.Timeout > 0 {
				if err := c.SetDeadline(time.Now().Add(conf.Timeout)); err != nil {
					return fmt.Errorf("unable to set timeout: %v", err)
				}
			}
			n, _, err := c.ReadFrom(b)
			if err != nil {
				if errors.Is(err, os.ErrDeadlineExceeded) {
					return nil
				}
				return fmt.Errorf("failed to read Ethernet frame: %v", err)
			}
			packetQueue <- append([]byte(nil), b[:n]...)
		}
	}
	return nil
}
